POST http://localhost:5000/api/auth/create
Content-Type: application/json

{
    "Username": "TestProfile14",
    "Password": "testprofile14",
    "Role": "Staff"
}
###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "Username": "TestProfile14",
    "Password": "testprofile14",
    "Role": "Staff"
}
###
POST http://localhost:5000/api/dataset/createAccount

###
POST http://localhost:5000/api/dataset/createAcademicYear
###
POST http://localhost:5000/api/dataset/createUserProfile

###
POST http://localhost:5000/api/dataset/createCategory

###
POST http://localhost:5000/api/dataset/createIdea

###
POST http://localhost:5000/api/dataset/createComment



###
GET http://localhost:5000/api/idea/home
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDA2MWExOGVjZDc0YzFmMTA4ZjgzMjQiLCJpYXQiOjE2NzgxMjMwNDh9.CELb38KZ9VpzuRE2WSZrhH_-y9DmaHNpkBk3NUkrpQ8

### 
GET http://localhost:5000/api/idea/profile/63e90e898afc6bc67b547656
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2U3YWE4ZjQwNzdmMjhmODdiZGI1MWYiLCJpYXQiOjE2NzYzMTE5MTB9.sY-2YROtz5vTcaC-VlGwtfdmJFVc7vW_r40_Apvxa1I

###
PUT http://localhost:5000/api/idea/63f466c857ae5bdd5d301350
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2U3YWE4ZjQwNzdmMjhmODdiZGI1MWYiLCJpYXQiOjE2NzYzOTEzNjl9.hog6yocs63pSdt0C3wtK26gcfy06Ch0fU8KVlNd4h_U
Content-Type: application/json

{
    "Title": "Test updateafsvfcng",
    "Description": "test update"
}

###
DELETE http://localhost:5000/api/idea/63f466c857ae5bdd5d301350
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2U3YWE4ZjQwNzdmMjhmODdiZGI1MWYiLCJpYXQiOjE2NzYzOTEzNjl9.hog6yocs63pSdt0C3wtK26gcfy06Ch0fU8KVlNd4h_U

### 
GET http://localhost:5000/api/category/showall
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2U3YWE4ZjQwNzdmMjhmODdiZGI1MWYiLCJpYXQiOjE2NzYzMTE5MTB9.sY-2YROtz5vTcaC-VlGwtfdmJFVc7vW_r40_Apvxa1I

###
POST http://localhost:5000/api/category/newCategory
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2U3YWE4ZjQwNzdmMjhmODdiZGI1MWYiLCJpYXQiOjE2NzYzMTE5MTB9.sY-2YROtz5vTcaC-VlGwtfdmJFVc7vW_r40_Apvxa1I
Content-Type: application/json

{
    "Title":"New category",
    "Description":"Create new category",
    "Status":"Openning"
}

###
PUT http://localhost:5000/api/category/update/63f36ea2880eeea5a8622ad6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2U3YWE4ZjQwNzdmMjhmODdiZGI1MWYiLCJpYXQiOjE2NzYzMTE5MTB9.sY-2YROtz5vTcaC-VlGwtfdmJFVc7vW_r40_Apvxa1I
Content-Type: application/json

{
    "Title":"Update category",
    "Description":"Create new category",
    "Status":"Openning"
}

###
DELETE http://localhost:5000/api/category/delete/63f36ea2880eeea5a8622ad6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2U3YWE4ZjQwNzdmMjhmODdiZGI1MWYiLCJpYXQiOjE2NzYzMTE5MTB9.sY-2YROtz5vTcaC-VlGwtfdmJFVc7vW_r40_Apvxa1I
//k duoc click
# ###
# POST http://localhost:5000/api/file/upload
# Content-Type: multipart/form-data; boundary=--------------------------785807947796125939618251

# Content-Disposition: form-data; name="IdeaId"
# Content-Type: text/plain

# "63e912385203710add850c31"

# --------------------------785807947796125939618251
# Content-Disposition: form-data; name="images"; filename="C:\Users\admin\Downloads\btn_after.jpg"
# Content-Type: image/jpeg

# ""

# --------------------------785807947796125939618251--

###
GET http://localhost:5000/api/file/download

###
GET http://localhost:5000/api/file/downloadzip

###
GET http://localhost:5000/api/user/myprofile/6407ffc56eb93c28c75cf0d3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2NDA3ZmZjNTZlYjkzYzI4Yzc1Y2YwZDIiLCJleHAiOjE2ODA4Mzc5MDUsImlhdCI6MTY3ODI0NTkwNX0.a57YZ-dcoz2UTeOecYRAkq-juUKHxTbiAUShOh-d5FM

###

PUT http://localhost:5000/api/user/updateProfile/6407ffc56eb93c28c75cf0d3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2NDA3ZmZjNTZlYjkzYzI4Yzc1Y2YwZDIiLCJleHAiOjE2ODA4Mzc5MDUsImlhdCI6MTY3ODI0NTkwNX0.a57YZ-dcoz2UTeOecYRAkq-juUKHxTbiAUShOh-d5FM
Content-Type: application/json

{
    "Name":"Hwng",
    "Gender":"Male",
    "PhoneNumber":"0123456789",
    "DoB": "2002-08-05",
    "Email": "hung@gmail.com",
    "Department": "Test",
    "Avatar": "Test",
    "AccountId": "64061a18ecd74c1f108f8324"
}

###
GET http://localhost:5000/api/profile/search/Test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDA2MWExOGVjZDc0YzFmMTA4ZjgzMjQiLCJpYXQiOjE2NzgxMjE1MDB9.2-T5DSWYRnJlAY4t-w2VyHBbVMy4-ELtsuRqlBoQpJk