POST http://localhost:5000/api/auth/create
Content-Type: application/json

{
    "Username": "tungy2s",
    "Password": "Manhtung1@",
    "Role": "Staff"
}
###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "Username": "DUcHung1",
    "Password": "123456",
    "Role": "Staff"
}
###
POST http://localhost:5000/api/auth/createAll

