POST http://localhost:5000/api/auth/create
Content-Type: application/json

{
    "Username": "tungy2s23",
    "Password": "Manhtung1@",
    "Role": "Staff"
}
###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "Username": "DUcHung1",
    "Password": "123456",
    "Role": "QAM"
}
###
POST http://localhost:5000/api/dataset/createAccount

###
POST http://localhost:5000/api/dataset/createUserProfile

###
POST http://localhost:5000/api/dataset/createCategory

###
POST http://localhost:5000/api/dataset/createIdea

###
POST http://localhost:5000/api/dataset/createComment

###
GET http://localhost:5000/api/idea/home
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2U3YWE4ZjQwNzdmMjhmODdiZGI1MWYiLCJpYXQiOjE2NzYzMTE5MTB9.sY-2YROtz5vTcaC-VlGwtfdmJFVc7vW_r40_Apvxa1I 