export const apiUrl = 'http://localhost:5000/api'
export const ACCOUNT_ID = 'accountId'
export const ROLE = 'role'
export const LOCAL_STORAGE_TOKEN_NAME = 'accessToken'
export const PROFILE_INFORMATION = 'profile_information'